name: Build Linux packages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Linux packages
        id: build-packages
        uses: love-actions/love-actions-linux@v2
        with:
          app-name: Tic Tac Toe
          bundle-id: com.example.ttt
          description: Tic Tac Toe game
          version-string: "0.0.1"
          icon-path: ./ttt/grid.png
          love-ref: "11.5"
          love-package: ./ttt/ttt.love
          lib-path: ./lib
          share-path: ./share
          build-deb: true
          product-name: ttt
          output-folder: ./dist

# Copy the built .AppImage into the ./ttt folder
      - name: Move AppImage to ttt directory
        run: |
          mkdir -p ./ttt
          cp ./dist/*.AppImage ./ttt/ || echo "No AppImage found"

# Upload artifacts so you can download them from the Actions tab
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: ./dist

