name: Build app for Tic-Tac-Toe (Android)

on:
  push:
    branches: [main]
    paths:
      - "tic-tac-toe/android/**"
      - ".github/workflows/ttt_buildandroid.yml"

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Love Android package
        id: build-love
        uses: love-actions/love-actions-android@v2
        with:
          app-name: "Tic-Tac-Toe"
          bundle-id: "com.example.ttt"
          resource-path: "./tic-tac-toe/android/resources"
          icon-specifier: "@mipmap/app"
          love-ref: "11.5"
          love-package: "./ttt/ttt.love"
          libs-path: ""
          extra-assets: ""
          product-name: "tic-tac-toe"
          output-folder: "./dist"
          keystore-alias: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
          keystore-base64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          keystore-key-password: ${{ secrets.ANDROID_KEYSTORE_KEYPASSWORD }}
          keystore-store-password: ${{ secrets.ANDROID_KEYSTORE_STOREPASSWORD }}

      # Move built APK to game folder
      - name: Move APK to intergalactic_game folder
        run: |
          mkdir -p ./tic-tac-toe/android/
          cp ./dist/*.apk ./tic-tac-toe/android || echo "No APK found"

      # Commit and push the APK back to the repo
      - name: Commit APK to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -f ./tic-tac-toe/android/*.apk
          git commit -m "Add built Android APK for TicTacToe" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload artifact so you can download from Actions tab
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ttt-android-build
          path: ./dist
